### PR TITLE
fs.fnl: Support platforms which appear to not use luajit

### PR DESCRIPTION
**Pull request by nickwanninger**
This patch simply updates the path-sep logic to follow the code referenced in the comment. This is required for aniseed to function correctly in my aarch64 ubuntu virtual machine.

### CODE REVIEW

**Comment by Olical** [comment]
Ohh interesting. So then you can require some of this outside of nvim / luajit? I'll take a look when I get home this evening.

**Comment by Olical** [comment]
Hmm am I right in saying this alternate method you added works for JIT too? Why don't we just use `(package.config:sub 1 1)` for all environments?

**Comment by Olical** [comment]
Can someone run `package.config:sub(1, 1)` on Windows for me and tell me if it returns `\`?

**Comment by nickwanninger** [comment]
Unfortunately I don't have a windows machine setup to test.

This patch was mainly to support gettng aniseed working in my ubuntu 20.04 vm, which I think had an old version of neovim *pre luajit* (~v0.4.3). I ended up compiling neovim from source and it solved the problem (v0.8.0). All depends on if you want to support ancient neovims :)

**Comment by Olical** [comment]
I think I'll close this! I'm pretty sure I depend on other features that require you to have a newer neovim, maybe around floating windows which are pretty core to the UX. So for now, I'll close this. But if I get people raising issues about this same thing where everything else should be supported I'll revisit this change. Thank you for the submission!

**Pull request closed without merging**
